import { createFileRoute, Link } from '@tanstack/react-router'

export const Route = createFileRoute('/terms')({
  component: TermsPage,
})

function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-[#E5E7EB] bg-white">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6">
          <Link to="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#1B4FFF]">
              <span className="text-sm font-black text-white">V</span>
            </div>
            <span className="text-lg font-bold text-[#0C0D0E]">ValiSearch</span>
          </Link>
          <Link to="/" className="text-sm font-medium text-[#52565E] hover:text-[#0C0D0E]">
            Back to home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
        <h1 className="text-4xl font-black text-[#0C0D0E] mb-8">Terms of Service</h1>
        <p className="text-sm text-[#52565E] mb-8">Last updated: May 2026</p>

        <div className="space-y-8 text-[#52565E] leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-[#0C0D0E] mb-3">1. Acceptance of Terms</h2>
            <p>By using ValiSearch, you agree to these terms. If you do not agree, do not use the service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0C0D0E] mb-3">2. Description of Service</h2>
            <p>ValiSearch provides AI-powered startup idea validation through 12 parallel analysis agents. Results are generated by artificial intelligence and are provided for informational purposes only. They do not constitute professional business, legal, or financial advice.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0C0D0E] mb-3">3. User Obligations</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must be at least 18 years old to use the service</li>
              <li>You are responsible for maintaining the confidentiality of your account</li>
              <li>You agree not to submit illegal, harmful, or infringing content</li>
              <li>You agree not to attempt to manipulate, reverse engineer, or abuse the AI system</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0C0D0E] mb-3">4. Credits and Payments</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>Each analysis consumes credits based on analysis type (Quick = 1, Full = 2)</li>
              <li>Credits are reset monthly according to your plan</li>
              <li>Unused credits do not roll over</li>
              <li>Payments are processed by LemonSqueezy. Refund requests are handled per LemonSqueezy's refund policy</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0C0D0E] mb-3">5. Limitation of Liability</h2>
            <p>ValiSearch provides analysis and recommendations based on AI models and publicly available data. We make no guarantees about the accuracy, completeness, or timeliness of any analysis. We are not liable for any business decisions made based on analysis results.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0C0D0E] mb-3">6. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may terminate your account at any time from the Settings page.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0C0D0E] mb-3">7. Changes to Terms</h2>
            <p>We may update these terms at any time. Continued use after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[#0C0D0E] mb-3">8. Contact</h2>
            <p>For questions about these terms: legal@valisearch.app</p>
          </section>
        </div>
      </main>

      <footer className="border-t border-[#E5E7EB] bg-gray-50">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-8 text-sm text-[#52565E] sm:px-6">
          <span>&copy; {new Date().getFullYear()} ValiSearch. All rights reserved.</span>
          <div className="flex gap-4">
            <Link to="/privacy" className="hover:text-[#0C0D0E]">Privacy</Link>
            <Link to="/terms" className="hover:text-[#0C0D0E]">Terms</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
